#!/usr/bin/env bash
set -euo pipefail

FENCE_BEGIN='<!-- BEGIN install-agent-context canonical (do not edit; regenerated by /install-agent-context) -->'
FENCE_END='<!-- END install-agent-context canonical -->'

GITIGNORE_FENCE_BEGIN='# BEGIN install-agent-context (do not edit; regenerated by /install-agent-context)'
GITIGNORE_FENCE_END='# END install-agent-context'
GITIGNORE_ENTRIES=(
  'AGENTS.md'
  'CLAUDE.md'
  '.agents/**'
  '.claude/**'
  '.cursor/**'
)

usage() {
  cat <<'USAGE'
Usage:
  install-agent-context.sh --source <path> --agent <claude|codex|copilot|cursor> [options]

Options:
  --target <path>     Repository root to update. Defaults to the current directory.
  --dry-run           Print planned actions without writing files.
  --skip-global       Do not update the global agent instruction file.
  --skip-repository   Do not update repository-local instruction files.
  -h, --help          Show this help.

Behavior notes:
- The repo root instruction file (CLAUDE.md / AGENTS.md) is written inside an HTML-comment
  fence so team-owned content in the same file is preserved. See SKILL.md.
- <target>/.gitignore is updated with a fenced block of sync-owned entries
  (AGENTS.md, CLAUDE.md, .agents/**, .claude/**, .cursor/**). Hand-authored
  ignores outside the fence are preserved.
- Cursor has no filesystem path for user-level (global) rules. --agent cursor prints an
  instruction to paste GLOBAL.md into Cursor Settings > Rules > User Rules and skips the
  global write. All other targets are written the same way as --agent codex.

Examples:
  scripts/install-agent-context.sh --source ~/personal-code/claude-setup --agent claude --target .
  scripts/install-agent-context.sh --source ~/personal-code/claude-setup --agent codex --target ~/work/app --dry-run
  scripts/install-agent-context.sh --source ~/personal-code/claude-setup --agent cursor --target .
USAGE
}

expand_path() {
  case "$1" in
    "~") printf '%s\n' "$HOME" ;;
    "~/"*) printf '%s/%s\n' "$HOME" "${1#~/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

absolute_dir() {
  local path
  path="$(expand_path "$1")"
  mkdir -p "$path"
  (cd "$path" && pwd -P)
}

copy_file() {
  local source_file="$1"
  local target_file="$2"
  local display_source="${3:-$source_file}"
  local action

  if [ ! -f "$source_file" ]; then
    printf 'MISSING source %s\n' "$display_source"
    return 1
  fi

  if [ -f "$target_file" ] && cmp -s "$source_file" "$target_file"; then
    printf 'SKIP current %s\n' "$target_file"
    return 0
  fi

  if [ -f "$target_file" ]; then
    action="REPLACE"
  else
    action="CREATE"
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'DRY-RUN %s %s <- %s\n' "$action" "$target_file" "$display_source"
    return 0
  fi

  mkdir -p "$(dirname "$target_file")"
  cp "$source_file" "$target_file"
  printf '%s %s\n' "$action" "$target_file"
}

transform_references() {
  local source_file="$1"
  local output_file="$2"
  local target_dir="$3"

  perl -0pe "
    s#\\.claude/context/CLAUDE\\.md#${target_dir}/context/AGENTS.md#g;
    s#\\.claude/styles/CLAUDE\\.md#${target_dir}/styles/AGENTS.md#g;
    s#\\.claude/context/#${target_dir}/context/#g;
    s#\\.claude/skills/#${target_dir}/skills/#g;
    s#\\.claude/styles/#${target_dir}/styles/#g;
    s#\\.claude/#${target_dir}/#g;
    s#\\.\\./context/CLAUDE\\.md#../context/AGENTS.md#g;
    s#\\.\\./styles/CLAUDE\\.md#../styles/AGENTS.md#g;
    s#\`CLAUDE\\.md\`#\`AGENTS.md\`#g;
  " "$source_file" > "$output_file"
}

copy_agent_file() {
  local source_file="$1"
  local target_file="$2"
  local transform_refs="$3"
  local target_doc_dir="${4:-.agents}"
  local tmp_file

  if [ "$transform_refs" -eq 0 ]; then
    copy_file "$source_file" "$target_file"
    return
  fi

  tmp_file="$(mktemp)"
  transform_references "$source_file" "$tmp_file" "$target_doc_dir"
  copy_file "$tmp_file" "$target_file" "$source_file"
  rm -f "$tmp_file"
}

copy_tree() {
  local source_dir="$1"
  local target_dir="$2"
  local rename_claude_files="$3"
  local transform_refs="$4"
  local target_doc_dir="${5:-.agents}"
  local source_file rel target_rel

  if [ ! -d "$source_dir" ]; then
    printf 'MISSING source directory %s\n' "$source_dir"
    return 1
  fi

  find "$source_dir" -type f | while IFS= read -r source_file; do
    rel="${source_file#"$source_dir"/}"
    target_rel="$rel"
    if [ "$rename_claude_files" -eq 1 ]; then
      case "$target_rel" in
        CLAUDE.md) target_rel="AGENTS.md" ;;
        */CLAUDE.md) target_rel="${target_rel%CLAUDE.md}AGENTS.md" ;;
      esac
    fi
    copy_agent_file "$source_file" "$target_dir/$target_rel" "$transform_refs" "$target_doc_dir"
  done
}

# Write the repo root instruction file with fenced sync-owned region so team
# content in the same file is preserved. Rules:
# - Target absent → create with just the fenced block.
# - Target present WITH fence markers → replace only the region between BEGIN
#   and END. Preserve everything before/after byte-for-byte.
# - Target present WITHOUT fence markers → prepend the fenced block plus a
#   blank line, then the existing content unchanged.
write_fenced_root_file() {
  local source_file="$1"
  local target_file="$2"
  local transform_refs="$3"
  local target_doc_dir="${4:-.agents}"

  if [ ! -f "$source_file" ]; then
    printf 'MISSING source %s\n' "$source_file"
    return 1
  fi

  # Materialize the canonical content (post reference transform, if any).
  local canonical_tmp
  canonical_tmp="$(mktemp)"
  if [ "$transform_refs" -eq 1 ]; then
    transform_references "$source_file" "$canonical_tmp" "$target_doc_dir"
  else
    cp "$source_file" "$canonical_tmp"
  fi

  # Build the desired final file contents in $desired_tmp.
  local desired_tmp
  desired_tmp="$(mktemp)"

  if [ ! -f "$target_file" ]; then
    {
      printf '%s\n' "$FENCE_BEGIN"
      # Strip trailing newlines from canonical (via $()) and re-add exactly
      # one, so the byte before FENCE_END is always a single \n. Matches the
      # awk REPLACE-path output for idempotent re-runs.
      printf '%s\n' "$(cat "$canonical_tmp")"
      printf '%s\n' "$FENCE_END"
    } > "$desired_tmp"
  elif grep -qF "$FENCE_BEGIN" "$target_file" && grep -qF "$FENCE_END" "$target_file"; then
    # Replace the fenced region in place. Use awk state machine to preserve
    # everything outside the fence and swap in the new canonical content.
    awk -v begin="$FENCE_BEGIN" -v end="$FENCE_END" -v new_file="$canonical_tmp" '
      BEGIN { in_fence = 0 }
      $0 == begin {
        print begin
        while ((getline line < new_file) > 0) print line
        close(new_file)
        print end
        in_fence = 1
        next
      }
      $0 == end {
        if (in_fence) { in_fence = 0; next }
        print
        next
      }
      { if (!in_fence) print }
    ' "$target_file" > "$desired_tmp"
  else
    # No fence in the target — prepend the fenced canonical block, blank
    # separator line, then existing content unchanged.
    {
      printf '%s\n' "$FENCE_BEGIN"
      printf '%s\n' "$(cat "$canonical_tmp")"
      printf '%s\n' "$FENCE_END"
      printf '\n'
      cat "$target_file"
    } > "$desired_tmp"
  fi

  # Compare desired vs current; emit CREATE / REPLACE / PREPEND / SKIP.
  local action
  if [ ! -f "$target_file" ]; then
    action="CREATE"
  elif cmp -s "$desired_tmp" "$target_file"; then
    printf 'SKIP fenced-current %s\n' "$target_file"
    rm -f "$canonical_tmp" "$desired_tmp"
    return 0
  elif grep -qF "$FENCE_BEGIN" "$target_file"; then
    action="REPLACE fenced-region in"
  else
    action="PREPEND fenced-block to"
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'DRY-RUN %s %s <- %s\n' "$action" "$target_file" "$source_file"
    rm -f "$canonical_tmp" "$desired_tmp"
    return 0
  fi

  mkdir -p "$(dirname "$target_file")"
  mv "$desired_tmp" "$target_file"
  printf '%s %s\n' "$action" "$target_file"
  rm -f "$canonical_tmp"
}

# Write agent-sync-owned entries into <target>/.gitignore inside a fenced
# region so any hand-authored ignores in the same file are preserved. Rules:
# - Target absent → create with just the fenced block.
# - Target present WITH fence markers → replace only the region between BEGIN
#   and END. Preserve everything before/after byte-for-byte.
# - Target present WITHOUT fence markers → append a blank separator line plus
#   the fenced block to the existing content.
# The set of entries matches what install-agent-context writes into any repo:
# AGENTS.md, CLAUDE.md, .agents/**, .claude/**, .cursor/**.
write_fenced_gitignore() {
  local target_file="$1"
  local desired_tmp
  desired_tmp="$(mktemp)"

  local block_tmp
  block_tmp="$(mktemp)"
  {
    printf '%s\n' "$GITIGNORE_FENCE_BEGIN"
    local entry
    for entry in "${GITIGNORE_ENTRIES[@]}"; do
      printf '%s\n' "$entry"
    done
    printf '%s\n' "$GITIGNORE_FENCE_END"
  } > "$block_tmp"

  if [ ! -f "$target_file" ]; then
    cp "$block_tmp" "$desired_tmp"
  elif grep -qF "$GITIGNORE_FENCE_BEGIN" "$target_file" && grep -qF "$GITIGNORE_FENCE_END" "$target_file"; then
    awk -v begin="$GITIGNORE_FENCE_BEGIN" -v end="$GITIGNORE_FENCE_END" -v new_file="$block_tmp" '
      BEGIN { in_fence = 0 }
      $0 == begin {
        while ((getline line < new_file) > 0) print line
        close(new_file)
        in_fence = 1
        next
      }
      $0 == end {
        if (in_fence) { in_fence = 0; next }
        print
        next
      }
      { if (!in_fence) print }
    ' "$target_file" > "$desired_tmp"
  else
    {
      cat "$target_file"
      if [ -s "$target_file" ] && [ "$(tail -c 1 "$target_file")" != "" ]; then
        printf '\n'
      fi
      printf '\n'
      cat "$block_tmp"
    } > "$desired_tmp"
  fi

  local action
  if [ ! -f "$target_file" ]; then
    action="CREATE"
  elif cmp -s "$desired_tmp" "$target_file"; then
    printf 'SKIP gitignore-current %s\n' "$target_file"
    rm -f "$block_tmp" "$desired_tmp"
    return 0
  elif grep -qF "$GITIGNORE_FENCE_BEGIN" "$target_file"; then
    action="REPLACE gitignore-region in"
  else
    action="APPEND gitignore-block to"
  fi

  if [ "$DRY_RUN" -eq 1 ]; then
    printf 'DRY-RUN %s %s\n' "$action" "$target_file"
    rm -f "$block_tmp" "$desired_tmp"
    return 0
  fi

  mv "$desired_tmp" "$target_file"
  printf '%s %s\n' "$action" "$target_file"
  rm -f "$block_tmp"
}

SOURCE=""
AGENT=""
TARGET="$PWD"
DRY_RUN=0
SKIP_GLOBAL=0
SKIP_REPOSITORY=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --source)
      SOURCE="${2:-}"
      shift 2
      ;;
    --agent)
      AGENT="${2:-}"
      shift 2
      ;;
    --target)
      TARGET="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --skip-global)
      SKIP_GLOBAL=1
      shift
      ;;
    --skip-repository)
      SKIP_REPOSITORY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [ -z "$SOURCE" ] || [ -z "$AGENT" ]; then
  usage >&2
  exit 2
fi

case "$AGENT" in
  claude|codex|copilot|cursor) ;;
  *)
    printf 'Unsupported agent: %s\n' "$AGENT" >&2
    usage >&2
    exit 2
    ;;
esac

SOURCE="$(expand_path "$SOURCE")"
if [ ! -d "$SOURCE" ]; then
  printf 'Source directory does not exist: %s\n' "$SOURCE" >&2
  exit 1
fi
SOURCE="$(cd "$SOURCE" && pwd -P)"

if [ "$DRY_RUN" -eq 1 ]; then
  TARGET="$(expand_path "$TARGET")"
else
  TARGET="$(absolute_dir "$TARGET")"
fi

case "$AGENT" in
  claude)
    GLOBAL_TARGET="$HOME/.claude/CLAUDE.md"
    ROOT_TARGET="$TARGET/CLAUDE.md"
    CONTEXT_TARGET="$TARGET/.claude/context"
    SKILLS_TARGET="$TARGET/.claude/skills"
    STYLES_TARGET="$TARGET/.claude/styles"
    TARGET_DOC_DIR=".claude"
    RENAME_CLAUDE_FILES=0
    ;;
  codex)
    GLOBAL_TARGET="$HOME/.codex/AGENTS.md"
    ROOT_TARGET="$TARGET/AGENTS.md"
    CONTEXT_TARGET="$TARGET/.agents/context"
    SKILLS_TARGET="$TARGET/.agents/skills"
    STYLES_TARGET="$TARGET/.agents/styles"
    TARGET_DOC_DIR=".agents"
    RENAME_CLAUDE_FILES=1
    ;;
  copilot)
    GLOBAL_TARGET="$HOME/.copilot/copilot-instructions.md"
    ROOT_TARGET="$TARGET/AGENTS.md"
    CONTEXT_TARGET="$TARGET/.agents/context"
    SKILLS_TARGET="$TARGET/.agents/skills"
    STYLES_TARGET="$TARGET/.agents/styles"
    TARGET_DOC_DIR=".agents"
    RENAME_CLAUDE_FILES=1
    ;;
  cursor)
    # Cursor has no filesystem path for user-level rules; those live in the
    # Cursor account (Settings > Customize > Rules). Repo-local layout is
    # identical to codex — AGENTS.md at root plus .agents/**.
    GLOBAL_TARGET=""
    ROOT_TARGET="$TARGET/AGENTS.md"
    CONTEXT_TARGET="$TARGET/.agents/context"
    SKILLS_TARGET="$TARGET/.agents/skills"
    STYLES_TARGET="$TARGET/.agents/styles"
    TARGET_DOC_DIR=".agents"
    RENAME_CLAUDE_FILES=1
    ;;
esac

if [ "$SKIP_GLOBAL" -eq 0 ]; then
  if [ -n "$GLOBAL_TARGET" ]; then
    copy_file "$SOURCE/GLOBAL.md" "$GLOBAL_TARGET"
  else
    # cursor: no supported filesystem target for user-level rules.
    printf 'MANUAL Cursor has no user-level rules file on disk. Paste %s into Cursor Settings > Customize > Rules > User Rules to sync globally.\n' "$SOURCE/GLOBAL.md"
  fi
fi

if [ "$SKIP_REPOSITORY" -eq 0 ]; then
  write_fenced_root_file "$SOURCE/CLAUDE.md" "$ROOT_TARGET" "$RENAME_CLAUDE_FILES" "$TARGET_DOC_DIR"
  copy_tree "$SOURCE/.claude/context" "$CONTEXT_TARGET" "$RENAME_CLAUDE_FILES" "$RENAME_CLAUDE_FILES" "$TARGET_DOC_DIR"
  copy_tree "$SOURCE/.claude/skills" "$SKILLS_TARGET" "$RENAME_CLAUDE_FILES" "$RENAME_CLAUDE_FILES" "$TARGET_DOC_DIR"
  copy_tree "$SOURCE/.claude/styles" "$STYLES_TARGET" "$RENAME_CLAUDE_FILES" "$RENAME_CLAUDE_FILES" "$TARGET_DOC_DIR"
  write_fenced_gitignore "$TARGET/.gitignore"
fi
